### ISSUE TITLE
Maaltijdcheques

### ISSUE THREAD

**Issue by Bart-VUTG** [Informatievlaanderen/OSLOthema-loongegevens#3]
Kunnen we een onderscheid maken tussen maaltijdcheques die wel of niet belastbaar zijn? Is er een mogelijkheid dit op te splitsen in het model?

"Maaltijdcheques worden beschouwd als een voordeel dat vrijgesteld is van sociale bijdragen en belastingen indien de voorwaarden bepaald in artikel 19bis van het Koninklijk besluit van 28 november 1969 en artikel 38/1, §2 van het Wetboek van de inkomstenbelastingen 1992 worden nageleefd."

https://werk.belgie.be/nl/themas/verloning/maaltijdcheques

**Comment by YvesMeersmans** [comment]
Bedankt voor de feedback. 
Dat onderscheid kan gemaakt worden, maar ik vraag me af of daar een goede reden voor is. Komt dit onderscheid van pas binnen jouw use case? Kan je ook jouw use case kort beschrijven?

**Comment by Bart-VUTG** [comment]
Dag Yves,

Voor onze use case vanuit het Groeipakket in het kader van de manuele alarmbelprocedure voor de sociale toeslagen houden we rekening met de bruto belastbare inkomsten.

De meeste maaltijdcheques zijn vrijgesteld van sociale zekerheidsbijdragen en er moeten geen inkomstenbelastingen op betaald worden. Deze maaltijdcheques worden niet meegerekend in het bruto belastbaar inkomen.

Maar wanneer een onderdeel van de maaltijdcheques belastbaar is dient dit wel bij het belastbaar inkomen toegevoegd te worden (analoog aan ecocheques?).

Als we in het model deze beide soorten maaltijdcheques kunnen opsplitsen krijgen we voor de use case vanuit het Groeipakket een correctere weergave van de inkomsten.

Groeten,
Bart - bart.maes@vutg.be

**Comment by YvesMeersmans** [comment]
Dag Bart,

Bedankt voor de input! We bekijken dit samen met de kerngroep en ik houd je op de hoogte. 

Groeten,
Yves

**Comment by Bart-VUTG** [comment]
Dag Yves,

Het is ons niet helemaal duidelijk of er naast de belastbare maaltijdcheques nog andere cheques bestaan die ook belastbaar zouden zijn (eco cheques, consumptiecheques,...?).

Indien deze ook bestaan, zouden we die ook graag opgenomen zien in het OSLO model.

Groeten,
Bart - bart.maes@vutg.be

**Comment by YvesMeersmans** [comment]
Emilie volgt dit inhoudelijk even verder op met jou en we bekijken met haar feedback mee of we hiervoor de attributen moeten wijzigen of niet.

**Comment by YvesMeersmans** [comment]
De volgende attributen zijn toegevoegd:
- belastbareMaaltijdcheques
- Cheques (om bv. ecocheques te kunnen opnemen)

Er is ook een nota gemaakt bij het attribuut 'supplementaireBelastbareBedragen', met de melding dat belastbare maaltijdcheques apart kunnen vermeld worden in het daarvoor voorziene attribuut. Dit om een dubbele telling te vermijden.
