### ISSUE TITLE
begrip schuldbemiddeling

### ISSUE THREAD

**Issue by sarahspiessens** [Informatievlaanderen/OSLOthema-loongegevens#5]
(opmerking verzameld bij OCMW Gent)
"Aangezien het hier gaat over een vocabularium mbt loongegevens, vermoed ik dat ze eigenlijk “collectieve schuldenregeling” en niet “schuldbemiddeling” bedoelen. Zeker omdat er verwezen wordt naar een schuldbemiddelaar, wat een begrip is dat normaal gezien enkel gebruikt wordt in het kader van een collectieve schuldenregeling.

Schuldbemiddeling heeft in principe betrekking op het onderhandelen over schulden met schuldeisers (al dan niet in combinatie met budgetbegeleiding of budgetbeheer) en heeft op zich niets te maken met het uitbetalen van loon. In de praktijk wordt die term soms wel gebruikt voor een collectieve schuldenregeling maar dat is eigenlijk niet correct.

Het zou dan ook beter zijn dat om de term “schuldbemiddeling” te vervangen door “collectieve schuldenregeling”. De omschrijving kan dan in principe wel behouden worden. Ik zou dan enkel nog “een instantie” wijzigen naar “een schuldbemiddelaar”."

**Comment by YvesMeersmans** [comment]
Het attribuut **_schuldbemiddeling_** zal in het applicatieprofiel en vocabularium worden aangepast naar ‘collectieve schuldenregeling’. De definitie nemen we over als volgt:
“Bij collectieve schuldenregeling wordt een schuldbemiddelaar ingeschakeld die een afbetalingsplan opstelt voor het betalen 
van schulden aan de schuldeisers. Het loon van een persoon wordt naar de schuldbemiddelaar gestort die het volgens de opgestelde regeling spendeert.”
