### ISSUE TITLE
ontbrekende loon-componenten

### ISSUE THREAD

**Issue by sarahspiessens** [Informatievlaanderen/OSLOthema-loongegevens#7]
Een aantal zaken die bvb bij OCMW Gent ook wel mee bekeken worden om "loon" te berekenen vinden we niet terug in het model.  Ik lijst ze hieronder op met kort een woordje uitleg hoe deze bij de berekening van het leefloon vervat worden. 

**- wijk-werken:** Wijk-werken is de vervanger van PWA in het Vlaams Gewest
Het gedeelte van het loon ten laste genomen door de uitgever van de Wijk-werkcheques en de eruit voortvloeiende vergoedingen zijn vrijgesteld voor een bedrag van 4,10 EUR per niet-ontwaarde Wijk-werkcheque. Hiervoor moeten deze voorwaarden wel voldaan zijn:
•	betaald aan betrokkene;
•	voor werkzaamheden verricht in het kader van een Wijk-werkovereenkomst;
•	overeenkomstig de terzake geldende reglementering.
Let op: dienstencheques zijn niet vrijgesteld en beschouwen we volledig als loon 

**- opzegvergoeding**
•	Heeft jouw cliënt recht op een opzegvergoeding na ontbinding van zijn arbeidscontract? Het bedrag van de opzegvergoeding neem je in rekening als inkomen voor de periode waarop de opzegvergoeding betrekking heeft.

**- inkomen uit sportactiviteiten**
Professionele sportbeoefenaars vallen onder een arbeidscontract of overeenkomst en komen daarom niet in aanmerking voor financiële hulpverlening. Eerste klasse voetbalclubs (Jupiler Pro League) zijn profclubs en tweede klasse voetbalclubs (Proximus League) zijn prof en semi-profclubs. Deze clubs hebben contractuele verplichtingen ten aanzien van spelers. Als jouw cliënt speelt voor een eerste of tweede klasse club dan heeft hij een arbeidscontract of -overeenkomst en verleen je hem geen financiële hulp. 

**- inkomen uit zelfstandige arbeid**

**- inkomen als onthaalouder**
De volgende regels gelden niet voor zelfstandige onthaalouders, maar voor onthaalouders gekoppeld aan een Organisator Gezinsopvang die een onkostenvergoeding krijgen i.p.v. loon.
Het inkomen als onthaalouder is niet vrijgesteld en neem je dus in rekening voor het berekenen van het leefloon. Let op: het deel van dit inkomen dat jouw cliënt besteedt aan beroepskosten (maaltijden, speelgoed…) is vrijgesteld. Vraag hiervan bewijs aan jouw cliënt

**- Inkomen uit leercontract of leervergoeding** 
**- inkomen uit tewerkstelling in de deeleconomie (vb deliveroo)**

**Comment by YvesMeersmans** [comment]
Dag Sarah,

Bedankt voor de feedback! We hebben dit naderbij bekeken.

Het traject van OSLO Loongegevens vandaag beperkt zich tot arbeidsloon, gedefinieerd als "Het bedrag dat een persoon ontvangt voor geleverde prestaties in **arbeidsverband**. Het kan gaan om een financieel bedrag, een bedrag in natura, vergoedingen, etc."
Het arbeidsverband is in deze context de betrekking tussen _werkgevers_ en _werknemers_ die ontstaat bij _loonarbeid_ na afsluiting van een _arbeidsovereenkomst_. 

Dit in het achterhoofd gehouden vallen volgens mij de suggesties buiten de scope van dit traject.
